### ISSUE TITLE
Make one-letter-circle optional

### ISSUE THREAD

**Issue by haary** [FredJul/Flym#200]
Since 1.7.6 a big circle with one letter is shown next to the entries. On small displays this is really disturbing. Please add an option to deactivate those circles.

**Comment by mhuhtala** [comment]
I'd consider removing the circles entirely from the individual feed views, since the letter/color is the same for all posts in one feed and doesn't carry any additional information. Or maybe put it in the feed title instead?

Also, the circles are about twice the size of those in the Gmail app, at least on my phone. They look pretty bad in comparison, and take up a lot of screen real estate.

**Comment by FredJul** [comment]
I personnally don't want to remove or make optional this letter: I tried and it's totally ugly when some feeds has an image and some others don't.

After I can also totally removed the image, but I also don't want to: for me it looks good and it's useful.
I'm really surprised of the noise this feature has made, I've received dozens of mails (and sometimes it almost looked like an insult). Why are you that surprised to see an image into a list?

I'll reduce a bit the size of the round image since it seems several people find it ugly, but I really think lot's of people just didn't understand that only the old entries does not have any images, the news ones will generally have one. Moreover, I suspect they also do not like when something change and they will get used to it after a while.

Or maybe I've missed something...

**Comment by FredJul** [comment]
I forgot to tell something, I'll make the size of the circle depending of the screen size. Like this small screens will have a really small circle, and the big ones the full size
