### ISSUE TITLE
Can't read Bleeping RSS Feed

### ISSUE THREAD

**Issue by Matthi3u** [FredJul/Flym#217]
Hi, I open this issue because I can't read Bleeping RSS Feed, I have this feed : http://www.bleepingcomputer.com/feed/ and http://www.bleepingcomputer.com/virus-removal/feed/ but when I try to update Flym I doesn't have any feed in result.

P.S : Sorry for my english I'm french.

**Comment by Urban82** [comment]
It's because the items in the feeds are too old: the newest item have date/time 03/02/2015 21:22 on the first one and 29/01/2015 20:11 on the last one.

Try to go to settings and change the "Time that the entries will be kept" (in french it should be "Délai de conservation des flux") to a greater value: with 2 weeks, in my phone I get 4 article for the first feed.

**Comment by Matthi3u** [comment]
Yeah that right, I don't check this, my bad....
