### ISSUE TITLE
Font contrast with background too low.

### ISSUE THREAD

**Issue by krelob** [FredJul/Flym#237]
Perhaps my phone doesn't have the best display but the gray font is difficult to read against the background color especially for read items.

**Comment by jotwewe** [comment]
I want to second this. While contrast is ok for unread items, read items are nearly unreadable (unless screen brightness is way too high and blinding once you look at something other than read items).

**Comment by Hez0** [comment]
The contrast for me is perfect for unread items. Using an Xt910, brightness at half (CM12).
Read items are a little dark, but I personally don't mind since I've already read them anyway.

Thanks for the lovely app.

**Comment by jotwewe** [comment]
In case I'm not interested in read items I do hide them, but when reading in the dark (very dim screen) and sometimes in other circumstances, they are just unreadable. I felt every other app to be bright enough in those cases.

Furthermore I don't think the difference between read and unread must be high -- in case I don't want to see unread items, I hide them anyway. For me it would even be fine to have read and unread entries display in the same colour.

**Comment by loneuron** [comment]
It's true that the read items are a little dark, but a larger issue is the dark text of new items.
It's bright enough to read it in house, but to dark to read it outside in the shadow.
I use the dark theme because I use a mobile phone with a AMOLED Display.

I wish a real white text color on a real black background. If this is someone to bright the display can be dimmed, but I can't increase the brightness/contrast of the current text color.
