### ISSUE TITLE
Edit links

### ISSUE THREAD

**Issue by Cotopaxi42** [FredJul/Flym#333]
Hi again,
Would it be possible to add an option to modify links (not only rename items)?
Thanks !

**Comment by afmbsr** [comment]
Hi, 

There are some suggestions. It's great to add them to flym

- Add zoom feature via two-finger spacing. Because some details in the pictures need not appear clearly

- Show feed link and logo while searching to add new feeds. Because sometimes show more than one feed with the same name

- Add an option to turn off notifications

Thank's

**Comment by FredJul** [comment]
this is delivered since yesterday ;)
