### ISSUE TITLE
Questions about the changes from 1.X to 2.X

### ISSUE THREAD

**Issue by hct0r** [FredJul/Flym#339]
Hi!

I've been using the previous versions of Flym (up to 1.9.1) for several years. It is a very nice app! It's awesome that the development continues! keep the good work! 

I just downloaded 2.0.6. It is a complete change. I was looking around to see if you posted any change log or the list of new/depreciated features from version 1 to 2, is there any?

Do you plan to get back : 
- the light theme?
- the icons in each feed?

Thanks!

**Comment by FredJul** [comment]
Hi,

No there is no such things as an official list of what I will/will not
include. Mainly because I can actually change my mind if there is good
arguments, and also because I don't know the time I'll need to do
everything (and if I'll ever do it).

But I can answer you on that two points:
- yes, I plan to add back white theme, but can't tell when
- if you speak about favicons then no, I don't want them anymore. There are
generally ugly (very small resolution) and we can't know when we need to
update them. Today I believe the colored letters to be simpler et good
enough.

Hope that answer your questions.

Fred

**Comment by hct0r** [comment]
Hi Fred, 

Thanks for the prompt reply,

This is another question that pop up during my migration to the new version:
Is there a way to edit/view feeds URL? 

Thanks

**Comment by FredJul** [comment]
Yes, you just need to long press on the feed and select "edit feed".

**Comment by hct0r** [comment]
So it's just a matter of time,

Thanks

**Comment by ildar** [comment]
Still needs the version on the About view
