### ISSUE TITLE
Option to disable "read/unread"

### ISSUE THREAD

**Issue by AeliusSaionji** [FredJul/Flym#340]
Hello!

Would it be too much of an inconvenience to have the option to just disable all unread tracking?

I know I'm in the minority here, but I personally consider tracking read status for RSS feeds to be more harmful than it is good. Social media has the right idea about not marking tweets/posts as read. In a high-volume environment, it does nothing but add a mental strain and an element of unnecessary micromanagement. I know when I've read something by virtue of having read it.

If I were the developer, I would just get rid of it 😉; despite the fact that the app description clearly says you have no interest in implementing syncing, I already see a feature request for syncing by owncloud.

Thanks!

**Comment by FredJul** [comment]
Well, I tend to disagree with you on that point. Having a "unread" feature is a must have for me since I want to know when something new arrived and don't want to have to detect what I have read or not. Using a social media is quite unpleasant for me mainly due to that.

Anyway, the read/unread feature is too deeply integrated into the app. I don't plan to remove it for now or even make it optional, sorry.

**Comment by CodingSpiderFox** [comment]
I agree with @FredJul
