### ISSUE TITLE
Feature request: Global filters

### ISSUE THREAD

**Issue by CodingSpiderFox** [FredJul/Flym#359]
At the moment, I think it is only possible to create filters for one feed at a time.

I'd like to filter out entries with a certain buzzword in all feeds at the same time.
At the moment, I need to create the filter for each feed. It should be much simpler.

**Comment by CodingSpiderFox** [comment]
Has the filter feature completely gone in the new version= :O

**Comment by FredJul** [comment]
Well, yes the filters are completely gone in the new v2. That doesn't mean I will not add them one day, but the previous implementation and UI was very bad and I would need to take time to do it in a better way this time.

**Comment by CodingSpiderFox** [comment]
What exactly was it you didn't like in the old implementation? In my opinion, the UI for the filters was OK.

**Comment by sknorr** [comment]
Well... there were deficiencies in the old version, IMO. There was no way to even know if your regular expression was valid and there was also no documentation which regex features were supported, if titles were matched or searched, or if case mattered.
Longer regexes were a pain, not just because you had to type them on a mobile device but also because the text box was too small, so you needed to scroll.
**But...** it was way better to have this than to not have any such feature.

**Comment by therussellhome** [comment]
The primary reason I love Flym is its filters (not the UI, the capability). I'm excited to see where v2 goes but I need to stick with the old version until the rest of the filter logic gets added.

**Comment by mitsnosrap** [comment]
@FredJul I believe this can be closed as the blacklist feature should provide this capability?

**Comment by FredJul** [comment]
again, you're right :)
