### ISSUE TITLE
The app is not available in Spain

### ISSUE THREAD

**Issue by kleiren** [FredJul/Flym#368]
The app shows as not available in the Play Store for Spain, is there any reason for that?

**Comment by FredJul** [comment]
Actually I did block my app on Spanish market, not because I wanted but because I received an email from spanish CEDRO association asking me to pay royalties for some strange reasons.


Since I do not receive any money for doing flym, I preferred to avoid any potential conflicts, hope you understand.

**Comment by kleiren** [comment]
...Incredible.

Sad for Spanish users then. We can actually get it from F-Droid, so at least there is an option.

Keep up the great work, amazing app!

**Comment by FredJul** [comment]
thanks, always glad to see message like this (it compensates the haters's messages ;) ).

**Comment by int-ua** [comment]
At first glance sounds like BS claim. What were the reasons? Was is really them or possible some scam? Just curious. Looks like they have a contanct email http://www.cedro.org/english
