### ISSUE TITLE
get logo from the website when a feed is added

### ISSUE THREAD

**Issue by linsui** [FredJul/Flym#395]
Use the logo of the website  instead of the name as the icon

**Comment by mchangeat** [comment]
Hello @FredJul, I implemented this feature.
Two questions so far:
- how do you localize strings in all the languages provided?
- are you interested in a merge request afterwards?

**Comment by FredJul** [comment]
Well, I'm not against an MR but I actually didn't implemented the favicon for three reasons :
- lot of favicons are too small and actually very ugly
- it's impossible to correctly cache it. You never know when it would change. Also, if you set some time policy (ie. keep them 1 month) and get the wrong one (for instance due to an airport wifi which doesn't allow to access to them until you're logged in), then you'll keep the airport icon on all feeds until the end of the cache expiration time.
- I myself almost doesn't care about the feed icon, I just want to read the articles I chosed and rarely check the source.

All in all, it seems to me much simpler to not handle it. So how did you handle it and how did you handle cases such as above?

**Comment by mchangeat** [comment]
Waw, you already had a pretty bad idea about this one!
I guess my answers will not be satisfactory enough...

- lot of favicons are too small and actually very ugly
That's right, I only used them on the left handside list where the size is small and adapted for favicons

- it's impossible to correctly cache it. You never know when it would change. Also, if you set some time policy (ie. keep them 1 month) and get the wrong one (for instance due to an airport wifi which doesn't allow to access to them until you're logged in), then you'll keep the airport icon on all feeds until the end of the cache expiration time.
I did not push the handling so far.
The favicons links are never updated at this time and if there are missing or so, the 2 letters picture will be used instead.

- I myself almost doesn't care about the feed icon, I just want to read the articles I chosed and rarely check the source.
It's a matter of personal taste and colours...

**Comment by wssyncmldm** [comment]
He has that thoughts because that's how it used to be in the past. When
Flym was still written in java and even before that when it used to be
called Feedex. Favicon used to be stored in db as blobs. I can see lots of
things have changed now. And those previous methods are not good way to
handle it.

It's better to keep letter icons than favicon

**Comment by mchangeat** [comment]
Alright.
But why do not closing this issue earlier with such explanations?
