### ISSUE TITLE
Particular articles not being fetched or fetched late

### ISSUE THREAD

**Issue by danburd** [FredJul/Flym#485]
Articles titled "Morning Notes" from this feed have not been fetched and displayed timely in Flym for as long as I've used the app (months):

https://www.arlnow.com/feed/

Sometimes they are fetched a day or two late. I'm unsure what is special about these articles but I've had no difficulty fetching anything else, that I know of. These Morning Notes are published every weekday morning so it should be simple to subscribe and see for yourself. An example of today's unfetched article is here:

https://www.arlnow.com/2019/06/03/morning-notes-2159/

The article is fetched by [Feeder](https://play.google.com/store/apps/details?id=com.nononsenseapps.feeder.play):

![Screenshot_20190603-154505](https://user-images.githubusercontent.com/4601223/58829856-dd32b080-8616-11e9-9a68-95e1e5dd2d6c.png)

Not by Flym:

![Screenshot_20190603-154533](https://user-images.githubusercontent.com/4601223/58829881-e9b70900-8616-11e9-95d2-2822c53a3f3a.png)

Thanks for the app, which works great otherwise. I appreciate your time.

**Comment by Batcastle** [comment]
I am having the same issue. My blog isn't getting updated in Flym. You can see the feed here:
https://draugeros.org/go/feed

I know it's not a problem with the feed itself because it's updating perfectly fine in Feedly. I have also tried changing refresh interval to no avail.

Finally, I know that my filter words will not remove it, and, I have tried force refreshing.

Could this possibly be something to do with the cache for websites that Android may keep?

**Comment by danburd** [comment]
It took almost a year for me to realize that, at least in my case, this was user error. I had the "Remove duplicates" setting checked. The daily articles I noted had identical titles so with that setting checked they would show up irregularly.
