### ISSUE TITLE
Error: Some of your feeds did not refresh correctly

### ISSUE THREAD

**Issue by tukusejssirs** [FredJul/Flym#512]
I’ve just installed Flym from Google Play, added Purism feed using thr built-in search and refreshed the feeds, then I got that error and can’t make it go away.
<img src="https://user-images.githubusercontent.com/5111894/61588986-92073980-ab93-11e9-81c6-2a33f93afd92.png" width="200">

**Comment by Locash** [comment]
The rss feeds belong to their respective websites (ie. Puri.sm )
Flym uses feedly's api for search queries. Feedly sources that data from its users and search engines. It is not always up to date.

1. **Check if the feeds address is correct.**
*Get the link that was used for the feed*
ᵖʳᵉˢˢ ≡ −−−> long press on name of feed −−−> press edit feed. 
Enter that feed's link into a browser, this shows the raw RSS\Atom data of that feed; way To check if the link is for a rss feed or not.

 **If bad:** go to website of interest and get the RSS link directly.⟨look for rss symbol⟩  Some sites may have multiple feeds; Yet only one feed link shows for a specific site in a search. Many use 3rd party sites to host their RSS data, because of this some feed don't have their sites name in the feed's link.

2. **Check if a feed validates**
A RSS feed is written in XML. If it has syntax errors(code errors) RSS readers can't pull the information needed. (_Its difficult to fix a upstream problem downstream._) 
Check with [W3C's RSS validator](https://validator.w3.org)

**Comment by Locash** [comment]
**_Feeds belong to their respective content creator and the raw XML data is their responsibility.**_
Flym uses feedly api for search queries, feedly sources that data from its users and search engines. It's not always up to date. 

**Always check if the feeds address is correct, if having sync issues.**

Puri.sm feed is not https://puri.sm/ which is what feedly search querie returns, it is 
https://puri.sm/feed/.

**Comment by tukusejssirs** [comment]
Correct! Just had time to check upon the issue. I read the original comment (in my email notification) and just wanted to same as you wrote in the new comment.

Anyway, first time it was added from the Flym menu, therefore, there still is an error (somewhere) in the rss adder.

Thank you!
